### ISSUE TITLE
Example on the Parameter Object

### ISSUE THREAD

**Issue by heldersepu** [dutradda/OpenAPI-Specification-2.1#1]
This was requested on the official OAS but got shutdown...

Would like to see `example` and `examples` on the Parameter Object
Just like we are doing for the OAS 3 Parameter Object:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject

**Comment by dutradda** [comment]
@heldersepu 
I think I have implemented the requested feature.
If it is OK for you, we can close the issue.

**Comment by heldersepu** [comment]
AwesomO !
hopefully the Guys atOAI will integrate

**Comment by heldersepu** [comment]
(unrelated to examples)
Something  I do not like is the **_required_** and **_mandatory_** items...

That will break backwards compatibility, forcing a lot of developer to refactor their tools.

**Comment by diogodafiti** [comment]
You are right, I removed these requires for backward compatibility.

**Comment by dutradda** [comment]
@heldersepu 
You are right, I already removed these requires for backward compatibility.
I think it is compatible now. The petstore example was passed on validation as well.

if you use python, you can run the validator your self.

pip install openapi21
openapi21-validator http://cdn.rawgit.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json http://cdn.rawgit.com/dutradda/OpenAPI-Specification-2.1/master/example/swagger.json
